### ISSUE TITLE
1) "before each" hook for "returns an authenticated user"

### ISSUE THREAD

**Issue by jadestrong** [caio-ribeiro-pereira/building-apis-with-nodejs#5]
When I run your code about mocha test,in the directory `test/routes/ ` if a test file follow closely `token.js`, it will always throw an error: 
```
Routes: Users
    GET /user
      status 200
Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/jadestrong/Documents/building-apis-with-nodejs/ntask-api/node_modules/sequelize/lib/dialects/sqlite/query.js:337:14)
    at Statement.afterExecute (/home/jadestrong/Documents/building-apis-with-nodejs/ntask-api/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/home/jadestrong/Documents/building-apis-with-nodejs/ntask-api/node_modules/sqlite3/lib/trace.js:20:31)

        1) "before each" hook for "returns an authenticated user"


  11 passing (4s)
  1 failing

  1) Routes: Users "before each" hook for "returns an authenticated user":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

```
after test,I found the reason is :
```
describe("Routes: Token", () => {
  const Users = app.db.models.Users;
  describe("POST /token", () => {
    beforeEach(done => {
      Users
        .destroy({where: {}})
        .then(() => Users.create({
          name: "John",
          email: "john@mail.net",
          password: "12345"
        }))
        .then(done());   // here should be `.then(() => done())`
    });
```
You can test it, and change the book's content about it.
English is not good, forgive me

**Comment by caio-ribeiro-pereira** [comment]
Thank you for this improvements! I'll fix it soon!
