### ISSUE TITLE
Error: bcrypt@0.8.7 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by openks** [caio-ribeiro-pereira/building-apis-with-nodejs#7]
Hi,
first of all, i really like your ebook! It's great!
when i install  with `sudo npm install` But i got a error,here is   
[npm-debug.txt](https://github.com/caio-ribeiro-pereira/building-apis-with-nodejs/files/670236/npm-debug.txt)

i searched baidu and google ,deleted ./node-gyp and reinstalled it ,i got the error too . 

i installed bcrypt@0.8.5 it doesn't work too.

```
zyxdeMacBook-Pro:ntask-api zyx$ python --version
Python 2.7.10
zyxdeMacBook-Pro:ntask-api zyx$ npm -v
3.10.9
zyxdeMacBook-Pro:ntask-api zyx$ node -v
v7.2.0

zyxdeMacBook-Pro:ntask-api zyx$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.2.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/zyx/code/building-apis-with-nodejs/ntask-api/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/zyx/.node-gyp/7.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/zyx/.node-gyp/7.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/zyx/code/building-apis-with-nodejs/ntask-api',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/zyx/code/building-apis-with-nodejs/ntask-api) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/zyx/code/building-apis-with-nodejs/ntask-api
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
zyxdeMacBook-Pro:ntask-api zyx$

```

[http://stackoverflow.com/questions/20911930/when-trying-to-configure-or-rebuild-node-gyp-getting-errors-mac-osx-mavericks](http://stackoverflow.com/questions/20911930/when-trying-to-configure-or-rebuild-node-gyp-getting-errors-mac-osx-mavericks) i tried all the posibility in this question , no  one works for me . 

i'm not sure if i offered enough info or not, if you need more info to position the error , let me know, thank you very much.

Is it possible that you can explain some tips to solve this problem here?

I would be very grateful.

**Comment by openks** [comment]
i got the answer 
```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```
the key is here !!
first of all ,i think it will be ok if i use the `sudo npm install`,but it is not ok ,here is the answer[http://stackoverflow.com/questions/32720476/agreeing-to-the-xcode-ios-license-requires-admin-privileges-please-re-run-as-ro](http://stackoverflow.com/questions/32720476/agreeing-to-the-xcode-ios-license-requires-admin-privileges-please-re-run-as-ro)

here is the answer:
this generally occurs after the mac OS update. All you need to do in terminal is run `sudo xcodebuild -license` and then agree to the terms. and then `npm install`is ok

it wasted me 2 days 
 thank you !
