### ISSUE TITLE
Cannot run server

### ISSUE THREAD

**Issue by pranjalnadhani** [caio-ribeiro-pereira/building-apis-with-nodejs#8]
After cloning the repo, I try to run the app using:
```shell
$ npm start
```
And after doing that, I get the following dump:
```shell
> ntask-api@1.0.0 start /home/pranjal/WebApps/nodejs-apis/ntask-api
> npm run apidoc && npm run clusters


> ntask-api@1.0.0 apidoc /home/pranjal/WebApps/nodejs-apis/ntask-api
> apidoc -i routes/ -o public/apidoc

info: Done.

> ntask-api@1.0.0 clusters /home/pranjal/WebApps/nodejs-apis/ntask-api
> babel-node clusters.js

fs.js:794
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir 'logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.<anonymous> (/home/pranjal/WebApps/nodejs-apis/ntask-api/libs/logger.js:5:6)
    at Module._compile (module.js:410:26)
    at loader (/home/pranjal/WebApps/nodejs-apis/ntask-api/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pranjal/WebApps/nodejs-apis/ntask-api/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
Cluster 30492 disconnected
Cluster 30492 is dead
NTask API - Port 3000
Cluster 30498 connected
NTask API - Port 3000
Cluster 30497 connected
NTask API - Port 3000
Cluster 30487 connected
NTask API - Port 3000
Cluster 30509 connected
```
But when I open the default URL `localhost:3000` then a server error shows up in my browser. When I try to `curl` into the default URL, I get this:

```shell
$ curl localhost:3000
curl: (52) Empty reply from server
```

**Comment by caio-ribeiro-pereira** [comment]
Try to remove the `logs` folder and try again.

**Comment by pranjalnadhani** [comment]
Now I am getting the following dump:

```shell
> ntask-api@1.0.0 start /home/pranjal/WebApps/nodejs-apis/ntask-api
> npm run apidoc && npm run clusters


> ntask-api@1.0.0 apidoc /home/pranjal/WebApps/nodejs-apis/ntask-api
> apidoc -i routes/ -o public/apidoc

info: Done.

> ntask-api@1.0.0 clusters /home/pranjal/WebApps/nodejs-apis/ntask-api
> babel-node clusters.js

NTask API - Port 3000
Cluster 31331 connected
NTask API - Port 3000
Cluster 31336 connected
NTask API - Port 3000
Cluster 31342 connected
NTask API - Port 3000
Cluster 31341 connected
```

But I still cannot run the server. The *Empty reply from server* error is still there!

**Comment by caio-ribeiro-pereira** [comment]
Could you show me the github of this project?

**Comment by pranjalnadhani** [comment]
It has been freshly cloned from your project without any change. I just issued the following commands:

```shell
$ git clone git@github.com:caio-ribeiro-pereira/building-apis-with-nodejs.git node-apis
```

```shell
$ cd node-apis/ntask-api
```

```shell
$ npm install
```

```shell
$ npm start
```

And that is where the problem arises.

**Comment by caio-ribeiro-pereira** [comment]
Did you try `curl https://localhost:3000`? Because the last version of my project is using fake SSL for simulate HTTPS environment.

**Comment by pranjalnadhani** [comment]
I am getting this:

```shell
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by caio-ribeiro-pereira** [comment]
Try to acccess https://localhost:3000 in your browser, I don't how to use curl well.

**Comment by pranjalnadhani** [comment]
Yes, it works in the browser, but I have to bypass the *Insecure connection* phase. Thanks a lot for the quick help!

Please mention this thing in the docs so other people don't face problems.

**Comment by caio-ribeiro-pereira** [comment]
Cool! I Updated the readme: https://github.com/caio-ribeiro-pereira/building-apis-with-nodejs/commit/947038430b687f6d640f46ca06293c552b6dbdf2
